/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // sideBarHome: [{type: 'autogenerated', dirName: '.'}],

  sideBarHome: [
    "home",
    "getting-started",
    {
      type: "category",
      label: "API",
      items: ["API/InsideAPI/Inside", "intro"],
    },
    "fi-server",
    // {
    //   type: "link",
    //   label: "Example link different sidebar click",
    //   href:"/tutorial-extras/manage-docs-versions",
    // },
    "sandbox",
    "changelog",
    {
      type: "category",
      label: "Products",
      items: [
        "products/duitnow-transfer",
        "products/duitnow-online-banking",
        "products/duitnow-qr",
        "products/duitnow-bill-payment",
        "products/mydebit",
        "products/fpx",
        "products/jompay",
      ],
      collapsed: false,
    },
  ],
  anotherSideBar: [
    {
      type: "html",
      value: '<a href="/home" style="display: flex; column-gap: 1rem; padding: 0 16px; color: #344054; text-decoration: none;"><img src="/img/chevron-left-black.png" alt="chevron-right" />Back</a>',      
    },
    "products/duitnow-transfer",
    {
      type: "category",
      label: "Overview",
      items: [
        {
          type: "category",
          label: "Credit Transfer",
          items: [
            "credit-transfer/introduction",
            "credit-transfer/credit-transfer-reversal",
          ],
        },
        "credit-transfer/nad"
      ],
    },
  ],
};

module.exports = sidebars;
