/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // sideBarHome: [{type: 'autogenerated', dirName: '.'}],

  sideBarHome: [
    "home",
    {
      type: "category",
      label: "Manual 1",
      items: ["API/InsideAPI/Inside", "intro"],
    },
    {
      type: "link",
      label: "Manage Docs Versions >",
      href:"/tutorial-extras/manage-docs-versions",
    },
    "tutorial-extras/translate-your-site",
    {
      type: "category",
      label: "Manual 2",
      items: ["tutorial-basics/create-a-blog-post"],
      collapsed: false,

    },
  ],
  anotherSideBar: [
    {
      type: "link",
      label: "Back",
      href: "/inside/inside-API",
    },
    "tutorial-extras/manage-docs-versions",
    "tutorial-basics/deploy-your-site",
  ],
};

module.exports = sidebars;
