/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // sideBarHome: [{type: 'autogenerated', dirName: '.'}],

  sideBarHome: [
    "home",
    "getting-started",
    {
      type: "category",
      label: "API",
      items: ["API/InsideAPI/Inside", "intro"],
    },
    "fi-server",
    // {
    //   type: "link",
    //   label: "Example link different sidebar click",
    //   href:"/tutorial-extras/manage-docs-versions",
    // },
    "sandbox",
    "changelog",
    "tutorial-basics/deploy-your-site",
    {
      type: "category",
      label: "Products",
      items: ["products/duidnow"],
      collapsed: false,

    }
  ],
  anotherSideBar: [
    {
      type: "link",
      label: "Back",
      href: "/inside/inside-API",
    },
    "tutorial-extras/manage-docs-versions",
    "tutorial-basics/deploy-your-site",
  ],
};

module.exports = sidebars;
